[phases.setup]
nixPkgs = ["python312", "poetry"]
aptPkgs = ["build-essential"]

[phases.install]
envs = { NIXPACKS_POETRY_VERSION = "2.1.1" }
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install poetry==${NIXPACKS_POETRY_VERSION}",
  "poetry config virtualenvs.create false",
  "poetry install --only main --no-interaction --no-ansi"
]

[start]
cmd = "poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT"