"""Add OAuth fields to User model

Revision ID: 14f5ff45a6e4
Revises: a556e12ab965
Create Date: 2025-03-25 18:56:28.518708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f5ff45a6e4'
down_revision: Union[str, None] = 'a556e12ab965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('oauth_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('oauth_data', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_column('users', 'oauth_data')
    op.drop_column('users', 'oauth_id')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
